# Generated by Django 3.2.8 on 2021-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ingredients',
            field=models.TextField(default=' '),
        ),
    ]
